// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/tokenization.proto

// Protobuf Java Version: 3.25.3
package com.tokenization.protobuf;

public final class listing_microservice {
  private listing_microservice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TokenizationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokenization.TokenizationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tokenId = 1;</code>
     * @return The tokenId.
     */
    java.lang.String getTokenId();
    /**
     * <code>string tokenId = 1;</code>
     * @return The bytes for tokenId.
     */
    com.google.protobuf.ByteString
        getTokenIdBytes();

    /**
     * <code>bytes chunk = 2;</code>
     * @return The chunk.
     */
    com.google.protobuf.ByteString getChunk();
  }
  /**
   * Protobuf type {@code tokenization.TokenizationRequest}
   */
  public static final class TokenizationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tokenization.TokenizationRequest)
      TokenizationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenizationRequest.newBuilder() to construct.
    private TokenizationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenizationRequest() {
      tokenId_ = "";
      chunk_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TokenizationRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tokenization.protobuf.listing_microservice.TokenizationRequest.class, com.tokenization.protobuf.listing_microservice.TokenizationRequest.Builder.class);
    }

    public static final int TOKENID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tokenId_ = "";
    /**
     * <code>string tokenId = 1;</code>
     * @return The tokenId.
     */
    @java.lang.Override
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenId_ = s;
        return s;
      }
    }
    /**
     * <code>string tokenId = 1;</code>
     * @return The bytes for tokenId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNK_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString chunk_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes chunk = 2;</code>
     * @return The chunk.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChunk() {
      return chunk_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tokenId_);
      }
      if (!chunk_.isEmpty()) {
        output.writeBytes(2, chunk_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tokenId_);
      }
      if (!chunk_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, chunk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tokenization.protobuf.listing_microservice.TokenizationRequest)) {
        return super.equals(obj);
      }
      com.tokenization.protobuf.listing_microservice.TokenizationRequest other = (com.tokenization.protobuf.listing_microservice.TokenizationRequest) obj;

      if (!getTokenId()
          .equals(other.getTokenId())) return false;
      if (!getChunk()
          .equals(other.getChunk())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKENID_FIELD_NUMBER;
      hash = (53 * hash) + getTokenId().hashCode();
      hash = (37 * hash) + CHUNK_FIELD_NUMBER;
      hash = (53 * hash) + getChunk().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tokenization.protobuf.listing_microservice.TokenizationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokenization.TokenizationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokenization.TokenizationRequest)
        com.tokenization.protobuf.listing_microservice.TokenizationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tokenization.protobuf.listing_microservice.TokenizationRequest.class, com.tokenization.protobuf.listing_microservice.TokenizationRequest.Builder.class);
      }

      // Construct using com.tokenization.protobuf.listing_microservice.TokenizationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        tokenId_ = "";
        chunk_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationRequest_descriptor;
      }

      @java.lang.Override
      public com.tokenization.protobuf.listing_microservice.TokenizationRequest getDefaultInstanceForType() {
        return com.tokenization.protobuf.listing_microservice.TokenizationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.tokenization.protobuf.listing_microservice.TokenizationRequest build() {
        com.tokenization.protobuf.listing_microservice.TokenizationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tokenization.protobuf.listing_microservice.TokenizationRequest buildPartial() {
        com.tokenization.protobuf.listing_microservice.TokenizationRequest result = new com.tokenization.protobuf.listing_microservice.TokenizationRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.tokenization.protobuf.listing_microservice.TokenizationRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.tokenId_ = tokenId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.chunk_ = chunk_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokenization.protobuf.listing_microservice.TokenizationRequest) {
          return mergeFrom((com.tokenization.protobuf.listing_microservice.TokenizationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tokenization.protobuf.listing_microservice.TokenizationRequest other) {
        if (other == com.tokenization.protobuf.listing_microservice.TokenizationRequest.getDefaultInstance()) return this;
        if (!other.getTokenId().isEmpty()) {
          tokenId_ = other.tokenId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getChunk() != com.google.protobuf.ByteString.EMPTY) {
          setChunk(other.getChunk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                tokenId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                chunk_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object tokenId_ = "";
      /**
       * <code>string tokenId = 1;</code>
       * @return The tokenId.
       */
      public java.lang.String getTokenId() {
        java.lang.Object ref = tokenId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tokenId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tokenId = 1;</code>
       * @return The bytes for tokenId.
       */
      public com.google.protobuf.ByteString
          getTokenIdBytes() {
        java.lang.Object ref = tokenId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tokenId = 1;</code>
       * @param value The tokenId to set.
       * @return This builder for chaining.
       */
      public Builder setTokenId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tokenId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string tokenId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTokenId() {
        tokenId_ = getDefaultInstance().getTokenId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string tokenId = 1;</code>
       * @param value The bytes for tokenId to set.
       * @return This builder for chaining.
       */
      public Builder setTokenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tokenId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chunk_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes chunk = 2;</code>
       * @return The chunk.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChunk() {
        return chunk_;
      }
      /**
       * <code>bytes chunk = 2;</code>
       * @param value The chunk to set.
       * @return This builder for chaining.
       */
      public Builder setChunk(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        chunk_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes chunk = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunk() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chunk_ = getDefaultInstance().getChunk();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tokenization.TokenizationRequest)
    }

    // @@protoc_insertion_point(class_scope:tokenization.TokenizationRequest)
    private static final com.tokenization.protobuf.listing_microservice.TokenizationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tokenization.protobuf.listing_microservice.TokenizationRequest();
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenizationRequest>
        PARSER = new com.google.protobuf.AbstractParser<TokenizationRequest>() {
      @java.lang.Override
      public TokenizationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TokenizationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenizationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tokenization.protobuf.listing_microservice.TokenizationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenizationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokenization.TokenizationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tokenURI = 1;</code>
     * @return The tokenURI.
     */
    java.lang.String getTokenURI();
    /**
     * <code>string tokenURI = 1;</code>
     * @return The bytes for tokenURI.
     */
    com.google.protobuf.ByteString
        getTokenURIBytes();
  }
  /**
   * Protobuf type {@code tokenization.TokenizationResponse}
   */
  public static final class TokenizationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tokenization.TokenizationResponse)
      TokenizationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenizationResponse.newBuilder() to construct.
    private TokenizationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenizationResponse() {
      tokenURI_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TokenizationResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tokenization.protobuf.listing_microservice.TokenizationResponse.class, com.tokenization.protobuf.listing_microservice.TokenizationResponse.Builder.class);
    }

    public static final int TOKENURI_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tokenURI_ = "";
    /**
     * <code>string tokenURI = 1;</code>
     * @return The tokenURI.
     */
    @java.lang.Override
    public java.lang.String getTokenURI() {
      java.lang.Object ref = tokenURI_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenURI_ = s;
        return s;
      }
    }
    /**
     * <code>string tokenURI = 1;</code>
     * @return The bytes for tokenURI.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenURIBytes() {
      java.lang.Object ref = tokenURI_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenURI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenURI_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tokenURI_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenURI_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tokenURI_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tokenization.protobuf.listing_microservice.TokenizationResponse)) {
        return super.equals(obj);
      }
      com.tokenization.protobuf.listing_microservice.TokenizationResponse other = (com.tokenization.protobuf.listing_microservice.TokenizationResponse) obj;

      if (!getTokenURI()
          .equals(other.getTokenURI())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKENURI_FIELD_NUMBER;
      hash = (53 * hash) + getTokenURI().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tokenization.protobuf.listing_microservice.TokenizationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokenization.TokenizationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokenization.TokenizationResponse)
        com.tokenization.protobuf.listing_microservice.TokenizationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tokenization.protobuf.listing_microservice.TokenizationResponse.class, com.tokenization.protobuf.listing_microservice.TokenizationResponse.Builder.class);
      }

      // Construct using com.tokenization.protobuf.listing_microservice.TokenizationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        tokenURI_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokenization.protobuf.listing_microservice.internal_static_tokenization_TokenizationResponse_descriptor;
      }

      @java.lang.Override
      public com.tokenization.protobuf.listing_microservice.TokenizationResponse getDefaultInstanceForType() {
        return com.tokenization.protobuf.listing_microservice.TokenizationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tokenization.protobuf.listing_microservice.TokenizationResponse build() {
        com.tokenization.protobuf.listing_microservice.TokenizationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tokenization.protobuf.listing_microservice.TokenizationResponse buildPartial() {
        com.tokenization.protobuf.listing_microservice.TokenizationResponse result = new com.tokenization.protobuf.listing_microservice.TokenizationResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.tokenization.protobuf.listing_microservice.TokenizationResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.tokenURI_ = tokenURI_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokenization.protobuf.listing_microservice.TokenizationResponse) {
          return mergeFrom((com.tokenization.protobuf.listing_microservice.TokenizationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tokenization.protobuf.listing_microservice.TokenizationResponse other) {
        if (other == com.tokenization.protobuf.listing_microservice.TokenizationResponse.getDefaultInstance()) return this;
        if (!other.getTokenURI().isEmpty()) {
          tokenURI_ = other.tokenURI_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                tokenURI_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object tokenURI_ = "";
      /**
       * <code>string tokenURI = 1;</code>
       * @return The tokenURI.
       */
      public java.lang.String getTokenURI() {
        java.lang.Object ref = tokenURI_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tokenURI_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tokenURI = 1;</code>
       * @return The bytes for tokenURI.
       */
      public com.google.protobuf.ByteString
          getTokenURIBytes() {
        java.lang.Object ref = tokenURI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenURI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tokenURI = 1;</code>
       * @param value The tokenURI to set.
       * @return This builder for chaining.
       */
      public Builder setTokenURI(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tokenURI_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string tokenURI = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTokenURI() {
        tokenURI_ = getDefaultInstance().getTokenURI();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string tokenURI = 1;</code>
       * @param value The bytes for tokenURI to set.
       * @return This builder for chaining.
       */
      public Builder setTokenURIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tokenURI_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tokenization.TokenizationResponse)
    }

    // @@protoc_insertion_point(class_scope:tokenization.TokenizationResponse)
    private static final com.tokenization.protobuf.listing_microservice.TokenizationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tokenization.protobuf.listing_microservice.TokenizationResponse();
    }

    public static com.tokenization.protobuf.listing_microservice.TokenizationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenizationResponse>
        PARSER = new com.google.protobuf.AbstractParser<TokenizationResponse>() {
      @java.lang.Override
      public TokenizationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TokenizationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenizationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tokenization.protobuf.listing_microservice.TokenizationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokenization_TokenizationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tokenization_TokenizationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokenization_TokenizationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tokenization_TokenizationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034resources/tokenization.proto\022\014tokeniza" +
      "tion\"5\n\023TokenizationRequest\022\017\n\007tokenId\030\001" +
      " \001(\t\022\r\n\005chunk\030\002 \001(\014\"(\n\024TokenizationRespo" +
      "nse\022\020\n\010tokenURI\030\001 \001(\t2j\n\023TokenizationSer" +
      "vice\022S\n\010Tokenize\022!.tokenization.Tokeniza" +
      "tionRequest\032\".tokenization.TokenizationR" +
      "esponse\"\000B1\n\031com.tokenization.protobufB\024" +
      "listing_microserviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tokenization_TokenizationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tokenization_TokenizationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tokenization_TokenizationRequest_descriptor,
        new java.lang.String[] { "TokenId", "Chunk", });
    internal_static_tokenization_TokenizationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tokenization_TokenizationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tokenization_TokenizationResponse_descriptor,
        new java.lang.String[] { "TokenURI", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
